### ISSUE TITLE
Leaderboard Bug

### ISSUE THREAD

**Issue by thatguys2good** [premiering/SkapNightly#19]
Leaderboard yet again broken due to the fact that ravelfett has updated how game ID's work. ID's are now 1,2,3,4,5 and any random # for private games.
1. Overworld
2. Precision Hell
3. Minimaps
4. Underworld
5. moonlit village

**Comment by premiering** [comment]
Will fix asap, thanks

**Comment by premiering** [comment]
Fixed, was because IP was blocked by ravel
